name: CI Build
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
jobs:
  NodeJSBuild:
    if: inputs.appType == 'nodejs'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: npm install
  MavenBuild:
    if: inputs.appType == 'maven'
    runs-on: self-hosted
    steps:
      - run: mvn package
  GoBuild:
    if: inputs.appType == 'golang'
    runs-on: self-hosted
    steps:
      - run: echo go build
  AngularBuild:
    if: inputs.appType == 'angular'
    runs-on: self-hosted
    steps:
      - run: echo angular build
