name: CI/CD - MAIN
on:
  workflow_call
jobs:
  NodeJSBuild:
    if: appType == 'nodejs'
    runs-on: self-hosted
    steps:
      - run: echo OK
  DEV:
    runs-on: self-hosted
    needs: Build
    steps:
      - run: echo OK