name: CI/CD - Main
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
jobs:
  Build:
    uses: nareshgdevops/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      appType: '${{ inputs.appType }}'
  TEST:
    uses: nareshgdevops/roboshop-github-actions/.github/workflows/test.yml@main
    with:
      appType: '${{ inputs.appType }}'
  DEV_DEPLOY:
    runs-on: self-hosted
    environment: DEV
    needs: TEST
    steps:
      - run: echo OK
  QA_DEPLOY:
    runs-on: self-hosted
    needs: DEV_DEPLOY
    environment: QA
    steps:
      - run: echo OK
  UAT_DEPLOY:
    runs-on: self-hosted
    needs: QA_DEPLOY
    environment: UAT
    steps:
      - run: echo OK
  PROD:
    runs-on: self-hosted
    needs: UAT_DEPLOY
    environment: PROD
    steps:
      - run: echo OK