name: CI/CD - MAIN
on:
  workflow_call
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - run: echo OK
  DEV:
    runs-on: self-hosted
    needs: Build
    steps:
      - run: echo OK
  TEST:
    runs-on: self-hosted
    needs: DEV
    steps:
      - run: echo OK