name: Dev Deploy
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
      docker_build:
        required: true
        type: string
    secrets:
      VAULT_TOKEN:
        required: true
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Import Vault Secrets
        if: inputs.docker_build == 'true'
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault.nareshdevops1218.online:8200/
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            roboshop-infra/data/azure-service-priniciple AZURE_SUBSCRIPTION_ID | AZURE_SUBSCRIPTION_ID ;
            roboshop-infra/data/azure-service-priniciple AZURE_CLIENT_ID | AZURE_CLIENT_ID ;
            roboshop-infra/data/azure-service-priniciple AZURE_SECRET | AZURE_SECRET ;
            roboshop-infra/data/azure-service-priniciple AZURE_TENANT | AZURE_TENANT ;

      - name: Docker Build
        if: inputs.docker_build == 'true'
        run: |
          az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_SECRET --tenant $AZURE_TENANT
          az acr login --name nareshgdevops
          docker build -t nareshgdevops.azurecr.io/roboshop-${{ inputs.appName }}:${{ github.sha }} .
          docker push nareshgdevops.azurecr.io/roboshop-${{ inputs.appName }}:${{ github.sha }}
