name: Dev Deploy
on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      aksName:
        required: true
        type: string
      resourceGroup:
        required: true
        type: string
    secrets:
      VAULT_TOKEN:
        required: true
jobs:
  DevDeploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          repository: nareshgdevops/roboshop-helm

      - name: Import Vault Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault.nareshdevops1218.online:8200/
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            roboshop-infra/data/azure-service-priniciple AZURE_SUBSCRIPTION_ID | AZURE_SUBSCRIPTION_ID ;
            roboshop-infra/data/azure-service-priniciple AZURE_CLIENT_ID | AZURE_CLIENT_ID ;
            roboshop-infra/data/azure-service-priniciple AZURE_SECRET | AZURE_SECRET ;
            roboshop-infra/data/azure-service-priniciple AZURE_TENANT | AZURE_TENANT ;

      - name: Deploy
        run: |
          az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_SECRET --tenant $AZURE_TENANT
          az acr login --name nareshgdevops
          az aks get-credentials --name ${{ inputs.aksName }} --resource-group ${{ inputs.resourceGroup }} --overwrite-existing
          helm upgrade -i ${{ inputs.appName }} . -f env-dev/${{ inputs.appName }}.yaml -n apps --create-namespace
