name: Build docker image for github runner
on:
  workflow_dispatch:
  push:
    paths:
      - 'runner-docker-image/**'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker build -t ng1218/github-runner .
          docker push ng1218/github-runner
          
